# Generated by Django 4.2.6 on 2023-12-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beslemekahramani',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_pictures'),
        ),
    ]
