# Generated by Django 4.2.6 on 2023-12-03 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0002_beslemekahramani_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beslemekahramani',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
