# Generated by Django 4.2.6 on 2023-12-10 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0004_alter_beslemekahramani_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('food_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='posts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_amount', models.FloatField(default=0)),
                ('feed_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MobileAPI.feedpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
