# Generated by Django 4.2.6 on 2023-12-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0006_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beslemekahramani',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='beslemekahramani',
            name='profile_picture',
        ),
    ]
