# Generated by Django 4.2.6 on 2023-12-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0008_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
