# Generated by Django 4.2.6 on 2023-12-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0009_post_is_active_report_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
