# Generated by Django 4.2.6 on 2024-01-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0010_remove_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpoint',
            name='food_avarage_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedpoint',
            name='food_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedpoint',
            name='last_calculated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedpoint',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
