# Generated by Django 4.2.6 on 2023-12-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0010_remove_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpoint',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
