# Generated by Django 4.2.6 on 2024-01-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0011_feedpoint_food_avarage_amount_feedpoint_food_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedpoint',
            name='food_avarage_amount',
            field=models.FloatField(default=0),
        ),
    ]
