# Generated by Django 4.2.6 on 2024-01-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0012_alter_feedpoint_food_avarage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpoint',
            name='should_update',
            field=models.BooleanField(default=True),
        ),
    ]
